# Simple workflow for deploying static content to GitHub Pages
name: Deploy storybook to Github Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          npm ci --legacy-peer-deps
          npm run build-storybook

      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v1
        with:
          branch: gh-pages
          folder: storybook-static
          token: ${{ github.token }}